# Generated by Django 3.0.3 on 2020-04-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img_name', models.CharField(max_length=30)),
                ('images', models.ImageField(upload_to='static/image/')),
            ],
        ),
    ]
