# Generated by Django 3.0.3 on 2020-04-03 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_cell', '0002_cases'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cases',
            new_name='Case',
        ),
    ]
