# Generated by Django 3.0.3 on 2020-04-03 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_cell', '0005_auto_20200403_2029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case',
        ),
    ]
