# Generated by Django 3.0.3 on 2020-04-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_cell', '0007_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='rphone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='case',
            name='vphone',
            field=models.IntegerField(),
        ),
    ]
