# Generated by Django 3.0.3 on 2020-04-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_cell', '0008_auto_20200403_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(default='Police', max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
