# Generated by Django 3.0.3 on 2020-04-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_cell', '0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
