# Generated by Django 3.0.3 on 2020-04-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_cell', '0015_auto_20200405_1700'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
