# Generated by Django 3.0.3 on 2020-04-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_cell', '0017_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
