# Generated by Django 3.0.3 on 2020-04-05 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_cell', '0019_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='image',
        ),
    ]
