# Generated by Django 3.0.3 on 2020-04-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_cell', '0020_remove_case_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='rphone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='case',
            name='vphone',
            field=models.CharField(max_length=30),
        ),
    ]
