# Generated by Django 3.0.3 on 2020-04-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_cell', '0021_auto_20200405_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='other',
            field=models.CharField(max_length=100),
        ),
    ]
